<#
.SYNOPSIS
    Fix Azure CLI authentication for external/guest users
    
.DESCRIPTION
    Performance Efficiency:
    - Non-interactive authentication (avoid blocking deployment)
    
    Reliability:
    - Validates credentials before proceeding
    - Handles external user tenant access
#>

param(
    [Parameter(Mandatory=$false)]
    [string]$TenantId = ""
)

$ErrorActionPreference = "Stop"

Write-Host "🔧 Fixing Azure CLI authentication (external user)..." -ForegroundColor Cyan
Write-Host ""

# Step 1: Get tenant ID from portal if not provided
if ([string]::IsNullOrWhiteSpace($TenantId)) {
    Write-Host "⚠️  Tenant ID required for external users" -ForegroundColor Yellow
    Write-Host ""
    Write-Host "Find your tenant ID:" -ForegroundColor Cyan
    Write-Host "1. Go to portal.azure.com" -ForegroundColor Gray
    Write-Host "2. Click your profile (top right) → Switch directory" -ForegroundColor Gray
    Write-Host "3. Find the directory with your subscription" -ForegroundColor Gray
    Write-Host "4. Copy the 'Tenant ID' (GUID format)" -ForegroundColor Gray
    Write-Host ""
    
    $TenantId = Read-Host "Enter Tenant ID (e.g., 12345678-1234-1234-1234-123456789abc)"
    
    if ([string]::IsNullOrWhiteSpace($TenantId)) {
        Write-Host "❌ Tenant ID required!" -ForegroundColor Red
        exit 1
    }
}

# Step 2: Clear cached credentials
Write-Host "✓ Clearing cached credentials..." -ForegroundColor Gray
az account clear

# Clear token cache
$tokenCachePath = "$env:USERPROFILE\.azure"
if (Test-Path $tokenCachePath) {
    Write-Host "✓ Clearing token cache..." -ForegroundColor Gray
    Remove-Item "$tokenCachePath\msal_token_cache.bin" -ErrorAction SilentlyContinue
    Remove-Item "$tokenCachePath\msal_token_cache.json" -ErrorAction SilentlyContinue
    Remove-Item "$tokenCachePath\accessTokens.json" -ErrorAction SilentlyContinue
    Remove-Item "$tokenCachePath\azureProfile.json" -ErrorAction SilentlyContinue
}

# Step 3: Login with explicit tenant (Reliability: external user access)
Write-Host "✓ Logging in to tenant: $TenantId..." -ForegroundColor Gray
Write-Host "   (Browser window will open)" -ForegroundColor Gray
Write-Host ""

# Performance: Use device code for external users (more reliable)
az login --tenant $TenantId --use-device-code

# Step 4: List subscriptions in this tenant
Write-Host ""
Write-Host "✓ Available subscriptions in tenant:" -ForegroundColor Gray
az account list --output table

# Step 5: Prompt for subscription selection
Write-Host ""
$subscriptionId = Read-Host "Enter Subscription ID from above list"

if ([string]::IsNullOrWhiteSpace($subscriptionId)) {
    Write-Host "❌ Subscription ID required!" -ForegroundColor Red
    exit 1
}

# Step 6: Set active subscription
Write-Host ""
Write-Host "✓ Setting active subscription..." -ForegroundColor Gray
az account set --subscription $subscriptionId

# Step 7: Verify access
$subscription = az account show --query "name" -o tsv

if ([string]::IsNullOrWhiteSpace($subscription)) {
    Write-Host "❌ Failed to access subscription!" -ForegroundColor Red
    Write-Host "" -ForegroundColor Yellow
    Write-Host "Possible issues:" -ForegroundColor Yellow
    Write-Host "1. You don't have Contributor/Owner role on this subscription" -ForegroundColor Gray
    Write-Host "2. Subscription is in a different tenant" -ForegroundColor Gray
    Write-Host "3. Guest user permissions not granted" -ForegroundColor Gray
    exit 1
}

Write-Host "✅ Authenticated successfully" -ForegroundColor Green
Write-Host "   Tenant: $TenantId" -ForegroundColor Gray
Write-Host "   Subscription: $subscription" -ForegroundColor Gray
Write-Host ""

# Step 8: Update extensions
Write-Host "✓ Updating Azure CLI extensions..." -ForegroundColor Gray
az extension update --name containerapp --only-show-errors
az extension update --name application-insights --only-show-errors

# Step 9: Save tenant ID for future use
$configContent = @"
# Azure configuration for external user
# Auto-generated by fix_azure_auth.ps1
TENANT_ID=$TenantId
SUBSCRIPTION_ID=$subscriptionId
"@

Set-Content -Path ".azure_config" -Value $configContent -Force
Write-Host "✓ Saved tenant config to .azure_config (for future runs)" -ForegroundColor Gray

Write-Host ""
Write-Host "✅ Azure CLI authentication fixed!" -ForegroundColor Green
Write-Host ""
Write-Host "Next steps:" -ForegroundColor Yellow
Write-Host "  .\scripts\demo_ready_from_container_for_azure.ps1" -ForegroundColor Gray
Write-Host ""
Write-Host "Note: You may need to add '--tenant $TenantId' to az commands" -ForegroundColor Yellow
Write-Host ""